LAN 574
alyf-de/landa pull request #177
Opened 2022-12-05 12:59 UTC by melanieroedel

First attempt by customization
Does not solve the problem discussed here: https://discuss.erpnext.com/t/disabling-mandatory-field-reference-no-in-payment-entry/63490/2

2022-12-06 13:35 UTC, barredterra requested changes, later dismissed
We don't need the property setters anymore, now that we have the default values, right?

2022-12-06 13:35 UTC, barredterra commented on landa/landa_sales/custom/payment_entry.json
> +  },
```suggestion
```

2022-12-06 18:17 UTC, melanieroedel commented on landa/landa_sales/custom/payment_entry.json
> +  },
I think we might. There is a strange double functionality as pointed out in the screenshots in the ticket.
Part of it is from this, part of it from an additional json file. So I decided to leave it in.
If you think we should take it out, feel free to delete it though!

2023-01-09 15:20 UTC, scdanieli approved these changes

2023-01-09 15:21 UTC, merged

2023-02-10 16:53 UTC, barredterra commented
:tada: This PR is included in version 0.2.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: