feat:"simple weight plausibility check (LAN-81)
alyf-de/landa pull request #215
Opened 2023-04-14 13:18 UTC by diePuppe

2023-04-14 13:25 UTC, barredterra requested changes

2023-04-14 13:25 UTC, barredterra commented on landa/water_body_management/custom/fish_species.json
Lieber direkt den DocType bearbeiten, statt über Customize Form zu gehen. Da wir selber definieren, wie der DocType aussehen soll, müssen wir ihn nicht zusätzlich customizen. Das stiftet nur Verwirrung.

2023-04-14 13:25 UTC, barredterra commented on landa/water_body_management/doctype/catch_log_entry/catch_log_entry.py
> +                )
```suggestion
			if (
				row.weight_in_kg < typical_weight * (1 - tolerance) or
				row.weight_in_kg > typical_weight * (1 + tolerance)
			):
				frappe.msgprint(
					frappe._("The weight of {0} in row {1} is not plausible").format(row.fish_species, row.idx)
				)

```

In python ist whitespace wichtig

2023-04-18 11:27 UTC, diePuppe reviewed
Änderung der Custom Form im richtigen Doctype durchgeführt

2023-04-18 13:53 UTC, barredterra requested changes
@diePuppe hast du die Funktionalität schon getestet?

Ich sehe aktuell noch folgende Probleme:

- Was passiert, wenn das Gewicht einer Fischart nicht hinterlegt ist?
- `frappe.db.get_value` gibt immer einen `string` zurück, den wir zuerst in einen `float` verwandeln müssen (bspw. per `from frappe.utils.data import flt`)
- Dem Feld _Typical Weight_ in der Fischart fehlt die Maßeinheit (besser: _Typical Weight in Kg_)
- Wir vergleichen aktuell das Gesamtgewicht der gefangenen Fische einer Art mit dem typischen Einzelgewicht.

2023-04-19 09:17 UTC, diePuppe commented
- [x]Das Gewicht wird auf Verfügbarkeit überprüft  
- [x] wird in Float verwandelt (ging aber auch vorher ?!)
- [x] Typical weight in KG hinzugefügt
- [x] Übersetzungsfehler gefunden
- [x] Gewicht wird noch durch Anzahl geteilt
- [x] Funktion überprüft, keine Mängel festgestellt

2023-04-19 14:27 UTC, barredterra requested changes

2023-04-19 14:27 UTC, barredterra commented on landa/fixtures/translation.json
> +  "translated_text": "Typisches Gewicht"
```suggestion
  "source_text": "Typical Weight in Kg",
  "translated_text": "Typisches Gewicht in Kg"
```

2023-04-19 14:27 UTC, barredterra commented on landa/water_body_management/doctype/fish_species/fish_species.json
> +    "fieldname": "typical_weight",
```suggestion
    "fieldname": "typical_weight_in_kg",
```

Die Maßeinheit ist auch im Code wichtig zu wissen, daher sollte sie auch im `fieldname` vorkommen.

2023-04-19 14:27 UTC, barredterra commented on landa/water_body_management/doctype/catch_log_entry/catch_log_entry.py
> +				#automatisierte E-Mail an den Verantwortlichen das Gewicht nach zu pflegen?
```suggestion
			typical_weight = flt(frappe.db.get_value("Fish Species", row.fish_species, "typical_weight_in_kg"))
			average_weight = row.weight_in_kg / row.amount
			if (
				typical_weight and
				average_weight < typical_weight * (1 - tolerance) or
				average_weight > typical_weight * (1 + tolerance)
			):
				frappe.msgprint(
					frappe._("The weight of {0} in row {1} is not plausible").format(row.fish_species, row.idx)
				)
```

- `frappe.utils.flt()` verwandelt `None` zu `0.0`, `float()` wirft einen Fehler
- `typical_weight` nicht zweimal aus der Datenbank laden
- `row.fish_species` ist kein Datenbankabruf. Daher bringt es nicht viel, das in eine Variable zu packen
- `else: pass` ist das Standardverhalten und muss nicht explizit aufgeschrieben werden

2023-04-24 08:26 UTC, diePuppe commented
Ein Test funktioniert nicht und stopt bei der Installation. 
Was bedeutet das?

2023-04-24 08:52 UTC, barredterra requested changes

2023-04-24 08:52 UTC, barredterra commented on landa/fixtures/translation.json
> +  "translated_text": "Das Gewicht des Fisches {0} in Reihe {1} ist nicht plausibel"
```suggestion
  "modified": "2023-04-24 10:55:08.320488",
  "name": "e5ddc15f05",
  "parent": null,
  "parentfield": null,
  "parenttype": null,
  "source_text": "The weight of {0} in row {1} is not plausible",
  "translated_text": "Das Gewicht von Fischart {0} in Zeile {1} ist nicht plausibel"
```

2023-04-24 11:04 UTC, merged

2023-05-08 16:09 UTC, barredterra commented
:tada: This PR is included in version 0.7.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: