feat: add sales report to ordermanagment (Lan 757 )
alyf-de/landa pull request #221
Opened 2023-05-26 14:47 UTC by diePuppe

2023-05-26 15:20 UTC, barredterra commented
Du musst das über die Benutzeroberfläche ändern, damit sich der "modified" timestamp auch aktualisiert. Sonst hat das bei einem Update keinen Effekt.

2023-06-03 07:41 UTC, diePuppe reviewed
Okay hab herausgefunden was der Fehler war.
Schönes Wochenende!

2023-06-03 07:41 UTC, diePuppe commented on landa/landa_sales/workspace/order_management/order_management.json
> + "modified": "2023-05-26 16:26:41.294828",
Gibt es noch einen? 
Hab die Reports über die Oberfläche geändert. Manchmal „hängt“, die aber und nimmt gemachte Änderungen nicht wieder raus. Wenn ich z.B den Hotfix wieder pulle ändert sich die Oberfläche nicht. Auch bei bench migrate ändert sie sich nicht. Konnte nicht ganz feststellen ab wann sie sich wieder resetet. Gibt es da nen speziellen Trick?

@barredterra

2023-06-03 12:52 UTC, barredterra approved these changes

2023-06-03 12:56 UTC, barredterra requested changes
Diese Häkchen müssten vermutlich aktiviert sein, sonst funktioniert der Link nicht. Das liegt daran, dass es unterschiedliche Arten von Berichten gibt, die unter verschiedenen Pfaden erreichbar sind. Daher muss man kennzeichnen, welche Art von Bericht man verknüpfen möchte.

2023-06-03 12:56 UTC, barredterra commented on landa/landa_sales/workspace/order_management/order_management.json
> +   "is_query_report": 0,
```suggestion
   "is_query_report": 1,
```

2023-06-03 12:56 UTC, barredterra commented on landa/landa_sales/workspace/order_management/order_management.json
> +   "is_query_report": 0,
```suggestion
   "is_query_report": 1,
```

2023-06-05 09:05 UTC, merged

2023-06-06 16:14 UTC, barredterra commented
:tada: This PR is included in version 0.8.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: