feat: auto date on stocking_target.js (LAN-58)
alyf-de/landa pull request #222
Opened 2023-05-26 16:09 UTC by diePuppe

2023-05-26 16:16 UTC, diePuppe commented
Hey Raffael,
gibt es ne Möglichkeit auf die Funktion von einem anderen DocType zuzugreifen?
Wollte das mit include machen, aber da meinte er das es nicht möglich ist.
liegt das daran das die Doctypes in anderen  apps sind?

2023-05-31 11:20 UTC, barredterra commented
In Zeile 4 wird ja der Code von `stocking_controller.js` eingebunden. Dieser wird sowohl in **Stocking Measure** als auch in **Stocking Target** verwendet. Macht es Sinn, die Funktion dort hinzuzufügen?

2023-06-03 07:09 UTC, diePuppe commented
Okay das hat funktioniert. Habe die andere Datei gleich mitgeändert oder brauch das nen eigenen PR?

2023-06-03 07:33 UTC, diePuppe reviewed
Okay, das hat funktioniert. Habe die andere yearly fishing permit gleich mitgeändert oder brauch das einen eigenen PR?

2023-06-03 13:05 UTC, barredterra requested changes

2023-06-03 13:05 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.js
> +{% include "landa/public/js/utils.js" %}
```suggestion
```

Die utils müssen hier nicht explizit eingebunden werden. Das passiert bereits hier:

https://github.com/alyf-de/landa/blob/33891e7126a4898af1a1328e83c49aace244645f/landa/hooks.py#L155

Damit sind die sowieso immer und überall verfügbar.

2023-06-03 13:05 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.js
Die Einrückung sollte auch in dieser Datei mit Tabs sein, wie im Rest der App.

2023-06-03 13:05 UTC, barredterra commented on landa/public/js/utils.js
> +}
Bitte auf eine einheitliche Formatierung achten

2023-06-05 13:05 UTC, barredterra requested changes

2023-06-05 13:05 UTC, barredterra commented on landa/public/js/utils.js
> +	}
```suggestion
	set_default_year: function set_default_year(frm) {
		// set default year to the current year if it's before november,
		// else to the next year
		const now = moment();
		let year = now.year();
		if (now.month() >= 11) {
			year += 1;
		}
		frm.set_value("year", year);
	}
```

2023-06-05 13:05 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.js
> +		landa.utils.set_default_year(frm);
```suggestion
		if (frm.is_new() && !frm.doc.year) {
			landa.utils.set_default_year(frm);
		}
```

Sonst wird das Jahr immer überschrieben, auch wenn es manuell geändert wurde.

2023-06-05 13:21 UTC, barredterra approved these changes

2023-06-05 13:21 UTC, merged

2023-06-06 16:14 UTC, barredterra commented
:tada: This PR is included in version 0.8.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.8.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: