water body api
alyf-de/landa pull request #223
Opened 2023-05-29 12:22 UTC by barredterra

- feat: water body api (LAN-764)
- docs: organization and water body API (LAN-764)

2023-06-06 08:55 UTC, marination requested changes

2023-06-06 08:55 UTC, marination commented on docs/cli.md
> +This app provide a bench command `make-demo-accounts`. This is useful for testing permissions. You can use it to create a **Member**, **Member Function** and **User** for every existing **Member Func
```suggestion
This app provides a bench command `make-demo-accounts`. This is useful for testing permissions. You can use it to create a **Member**, **Member Function** and **User** for every existing **Member Function Category**, in an existing local organization.
```

2023-06-06 08:55 UTC, marination commented on docs/cli.md
> +This app provide a bench command `import-geojson`. This is useful for importing water body shapes from a GeoJSON file.
```suggestion
This app provides a bench command `import-geojson`. This is useful for importing water body shapes from a GeoJSON file.
```

2023-06-06 08:55 UTC, marination commented on landa/commands/__init__.py
> +		feature["properties"].pop("GEW_NA")
Import breaks if there is no `GEW_NA` key. Is this key mandatory like the `GEW_ID` key. If so it must be mentioned in the docs or else handled.
```py
 File ".../apps/landa/landa/commands/__init__.py", line 132, in import_features
    feature["properties"].pop("GEW_NA")
KeyError: 'GEW_NA'
```

2023-06-06 08:55 UTC, marination commented
Tested the rest. LGTM after changes are resolved.

2023-06-07 12:06 UTC, marination approved these changes, later dismissed

2023-06-07 12:06 UTC, marination commented
@barredterra good to merge?

2023-06-08 14:35 UTC, barredterra commented
@marination there is still an outstanding feature (custom markers) that was supposed to be part of this PR. Let's keep this open for now. I'll check with the customer if we should merge this as a first step.

2023-06-13 09:59 UTC, merged

2023-06-14 14:41 UTC, barredterra commented
:tada: This PR is included in version 0.9.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: