feat: LAN-45 hide custom allways 1
alyf-de/landa pull request #225
Opened 2023-06-20 08:40 UTC by diePuppe

Hey Raffael,
wo kann ich die Workspace_hooks.py abspeichern, dass die nicht so wild dort herumliegt?

Grüße
Tim

2023-06-29 06:37 UTC, barredterra requested changes
Ich würde die Datei in `workspace.py` umbenennen und dort liegen lassen, wo sie ist. Es gibt eigentlich einen Ordner, wo sie besser hinpassen würde.

2023-06-29 06:37 UTC, barredterra commented on landa/workspace_hooks.py
> +            frappe.msgprint("Die Checkbox 'Hide Custom' wurde automatisch auf 1 gesetzt.")
```suggestion
	if (
		doc.for_user and
		doc.hide_custom == 0 and
		doc.extends in ("Water Body Management", "Organization Management", "Order Management")
	):
		doc.hide_custom = 1
```

Wir sollten sicherstellen, dass wir die checkbox nur nur für unsere eigenen, durch den Benutzer angepassten Workspaces setzen. In andere Apps und Standard-Workspaces wollen wir uns nicht einmischen.

2023-06-29 16:18 UTC, diePuppe commented
Hey Raffael hab das mit dem pre-commit gemacht. Läuft auch durch alles durch, aber auf github kommen dann die ganzen Tests nicht durch.

![grafik](https://github.com/alyf-de/landa/assets/95628567/b742dfd1-77d3-4834-83bf-ea21fc992f17)

2023-06-30 13:26 UTC, barredterra commented
@diePuppe sehr gut. Alles, was precommit betrifft,b läuft jetzt schonmal fehlerfrei durch.

Der eine Fehler war noch, dass du keine _conventional commit_ Titel verwendet hast, aber das ist nicht so tragisch.

Und für den anderen Fehler kannst du nichts, den muss ERPNext beheben.


Aber die `hooks.py` sollten wir auf keinen Fall löschen!

2023-07-07 11:34 UTC, closed without merging