feat: LAN-699 link contact_person
alyf-de/landa pull request #226
Opened 2023-06-20 15:45 UTC by diePuppe

Hey Raffael,

kannst du mir kurz weiterhelfen? 
Ich kriege die Throw Funktion nicht. 

Failed to get method for command landa.organization_management.doctype.landa_member.link_contact_person with module 'landa.organization_management.doctype.landa_member' has no attribute 'link_contact_person'

Weiß, irgendwie nicht mehr weiter woran es liegen könnte

2023-06-29 06:49 UTC, barredterra requested changes
Achte bitte auf die korrekte Formatierung. Du kannst dir auch [pre-commit](https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#linting) im Verzeichnis `apps/landa` installieren, damit das automatisch bei jedem Commit gemacht wird.

2023-06-29 06:49 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.js
> +                method: 'landa.organization_management.doctype.landa_member.link_contact_person',
```suggestion
                method: 'landa.organization_management.doctype.landa_member.landa_member.link_contact_person',
```

So müsste es funktionieren.

```
/app /modul                  /ordner /ordner      /datei        /funktion
landa.organization_management.doctype.landa_member.landa_member.link_contact_person
```

2023-06-30 13:05 UTC, diePuppe commented
Hey Raffael, 
Funktion ist erstmal nur für die Adresse gegeben, da die (jedenfalls die erste) immer gleich beschriftet wird. 
Bei Contact sieht Das schon schwieriger aus, da der Name über die Eingabe des Users vergeben wird.
Hast du noch einen Ansatz, wie man auf das HTML zugreifen kann, obwohl sich der Name aus diesem heraus ergibt? 
Außerdem habe ich noch das Problem, dass die Adresse Änderung nur funktioniert, solange eine Adresse angegeben ist. 
Wenn keine Adresse in der Organisation angegeben ist, funktioniert nämlich mein Aufruf nicht mehr.
Beste Grüße
Tim

2023-07-18 16:01 UTC, barredterra requested changes

2023-07-18 16:01 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.js
> +		frm.add_custom_button(__('Linking as Contact Person'), function() {
```suggestion
		frm.add_custom_button(__("Set as Contact Person"), function() {
```

2023-07-18 16:01 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.js
Im Rest der Datei werden doppelte Anführungszeichen verwendet. Das sollte so beibehalten werden.

2023-07-18 16:01 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.js
> +
```suggestion

```

Eine Leerzeile am Ende reicht

2023-07-18 16:01 UTC, barredterra commented on landa/fixtures/translation.json
> + },
Hat nichts mit diesem Pull Request zu tun

2023-07-18 16:01 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.py
> +	)
Hier würde ich über alle Adressen und Kontakte iterieren, die mit dem **LANDA Member** verknüpft sind, und diese dann sicherstellen dass diese mit der entsprechenden **Organization** und **Customer** verknüpft sind (entweder bereits vorhanden oder neu hinzufügen).

2023-07-18 16:01 UTC, barredterra commented on landa/organization_management/doctype/landa_member/landa_member.py
> +	organization_address.delete()
Nicht löschen, nur die Verknüpfung entfernen!

2023-08-08 10:26 UTC, diePuppe commented
Hallo @barredterra,
hab das jetzt mit Link und unlink umgesetzt, außerdem wird die Adresse automatisch aktualisiert, wenn die Adresse beim Member geändert wird. 

[Uploading Bildschirmaufzeichnung vom 08.08.2023, 12:16:15.webm…]()

2023-08-08 10:52 UTC, diePuppe commented
Hallo @barredterra,
hab das jetzt mit Link und unlink umgesetzt, außerdem wird die Adresse automatisch aktualisiert, wenn die Adresse beim Member geändert wird.

[Bildschirmaufzeichnung vom 08.08.2023, 12:16:15.webm](https://github.com/alyf-de/landa/assets/95628567/caa79248-76fe-48ef-80a6-ae28080ba1e9)

2023-08-14 23:42 UTC, barredterra commented
Closing in favor of https://github.com/alyf-de/landa/commit/ab0ca7f3ccce1b6139c8c8870fbc719d2103ab39

2023-08-14 23:42 UTC, closed without merging