feat: wip (LAN-85)
alyf-de/landa pull request #239
Opened 2023-08-13 09:48 UTC by scdanieli

2023-08-14 19:10 UTC, barredterra requested changes

2023-08-14 19:10 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.py
> +		self.save()
```suggestion
```

2023-08-14 19:10 UTC, barredterra commented on landa/water_body_management/doctype/stocking_measure/stocking_measure.py
> +		frappe.get_doc("Stocking Target", self.stocking_target).update_status()
```suggestion
		st = frappe.get_doc("Stocking Target", self.stocking_target)
		st.update_status()
		st.save()
```

2023-08-14 19:10 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.py
`update_status()` müsste auch aufgerufen werden, wenn sich die Menge in **Stocking Target** ändert. Damit das funktioniert, sind die anderen beiden Änderungen nötig. (Was mich zu der Annahme bringt, dass Methoden mit `self.save()` grundsätzlich schlecht wiederverwendbar sind.)

2023-08-21 15:44 UTC, scdanieli commented on landa/water_body_management/doctype/stocking_target/stocking_target.py
Ich stimme dem zu und habe den Code entsprechend angepasst.

2023-08-21 16:56 UTC, barredterra commented on landa/water_body_management/doctype/stocking_target/stocking_target.py
> +		self.update_status()
```suggestion
		self.update_status()
```

2023-08-21 16:56 UTC, barredterra commented on landa/water_body_management/stocking_controller.py
> +
```suggestion
```

2023-08-21 16:56 UTC, barredterra commented on landa/water_body_management/stocking_controller.py
> +
Wenn es nichts tut, brauchen wir das nicht mehr, oder?

2023-08-21 17:08 UTC, scdanieli commented on landa/water_body_management/stocking_controller.py
> +
Ich persönlich würde die Änderungen nicht vornehmen, um potentielle Fallstricke in der Zukunft zu vermeiden. Falls dem Controller in Zukunft eine `before_validate`-Funktion hinzugefügt wird. https://github.com/alyf-de/landa/blob/6fa17ba612c723ea38d27a16d658ba0172a9e1f9/landa/water_body_management/stocking_controller.py#L19-L21 z.b. gehört ja eigentlich in eine `before_validate`-Funktion. Ich habe allerdings kein Refactoring durchgeführt, da es nicht Teil der Aufgabe war und ich keine Zeit aufwenden wollte, um über potentielle Probleme bei einer Anpassung nachzudenken ...

Zusammengenommen sind deine beiden Vorschläge aber valide falls du diese Anpassung drin haben möchtest.

2023-08-21 17:43 UTC, barredterra commented on landa/water_body_management/stocking_controller.py
> +
Eins von beiden fände ich gut, also entweder das Refactoring oder die leere Methode entfernen.

2023-08-21 22:43 UTC, scdanieli commented on landa/water_body_management/stocking_controller.py
> +
Erledigt. Und dabei noch einen Uralt-Fehler gefunden. 😮‍💨

2023-08-22 08:33 UTC, barredterra approved these changes

2023-08-22 14:59 UTC, merged

2023-10-19 09:30 UTC, barredterra commented
:tada: This PR is included in version 0.11.0 :tada:

The release is available on [GitHub release](https://github.com/alyf-de/landa/releases/tag/v0.11.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: